###
# build multistage dockerfile. to build base and prod image exec:
# $> docker compose build
# to install a specific repo or branch on prod image :
# $> REPO_SRC="https://repo.git" REPO_BRANCH="dev_branch" docker compose build
###


services:

  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
      target: base
    image: afis_gui_base

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        - REPO_BRANCH=${REPO_BRANCH:-master}
        # - REPO_SRC= use it to change repo
    depends_on:
      - base
    image: afis_gui_prod:${REPO_BRANCH:-latest}


